### ISSUE TITLE
Issue with `ChatMessage` source 

### ISSUE THREAD

**Issue by reonZ** [7H3LaughingMan/foundry-pf2e#27]
Making an issue from the discord message to avoid it being lost

i didn't make a PR because i dunno how or where it should be resolved but there is still some issue with `ChatMessage`, right now, if i do 
```js
const messageSource = message.toObject();
CHatMessage.create(messageSource)
``` 
i get an error saying that whisper doesn't accept `null`

the whisper field is
 ```js
whisper: fields.ArrayField<fields.ForeignDocumentField<string>>;
``` 
which means that its type is `(string|null)[]` which doesn't makes much sense, why would the array contain null ?

so on my local i changed the schema itself to
```js
whisper: fields.ArrayField<fields.ForeignDocumentField<string, true, false>>;
``` 
and it solves the issue, but i dunno if this is an appropriate change

**Comment by 7H3LaughingMan** [comment]
The third parameter of `ForeignDocumentField` sets if the value can be nullable, which is why it was thinking it could be a `string | null` before it's passed onto `ArrayField`.

**Comment by reonZ** [comment]
so my solution was the right one in the end !!
